# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 2.1.302

branches:
  only:
  - dotnet-core

services:
  - docker
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:

  
script:
   - psql -c "create database roadkill;" -U postgres
   - psql -c "CREATE USER roadkill WITH PASSWORD 'roadkill';" -U postgres
   - psql -c "ALTER USER roadkill WITH SUPERUSER;" -U postgres
   - docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.2.4
   - dotnet restore
   - dotnet build -c Release  
   - pushd src/Roadkill.Tests
   - dotnet test
   - popd